### ISSUE TITLE
A1 - Injection Attacks:  machine input additional vectors

### ISSUE THREAD

**Issue by bandrzej** [OWASP/Top10#240] opened 2017-10-24 17:52 UTC
What about the attack vectors of reading in application variables from these *machine input* sources?

- Application configuration files  (i.e. application.properties for Java, app.config for C#/.Net)
- OS/container environment variables for input validation

Should these be an additional scenario for necessary input validation for acceptable values and lengths for runtime and/or possible READ ONLY to prevent tampering?

Or would this be a BETTER fit under "A6 - Security Misconfiguration"?

Majority of SASTs will detect as "Input validation" and/or "Path Manipulation" if it uses a file path to read something like a keystore or other config files.

With the proliferation of automated deployment pipelines, the application can be altered at the source code repository level and possibly pass all automated checks in its journey into production.

**Comment by Neil-Smithline** [comment] 2017-10-25 15:48
This feels more A1:2017 than A6:2017 to me, though either could work. The problem is that we just don't have space. I think that the SQL and Hibernate examples currently in A1:2017 are more important. Even if we deleted one of them, I'm just not sure how we could fit a separate example there. I also looked at adding something to one of the other boxes. But I think the T10 should focus on attack vectors more common than source code being modified by an attacker. That's simply out of scope for such a small document.

BTW, I do not see an OWASP cheat sheet on environment injection or similar topics. Perhaps we could squeeze in a reference to one if a domain expert were to write one. OWASP.org is a wiki that allows anyone to register and then edit, if you're interested.

**Closed by Neil-Smithline** 2017-10-25 15:48 UTC
Labels: A1
